# Generated by Django 3.0.8 on 2020-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('date_of_use', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Не активована'), ('2', 'Активована'), ('3', 'Прострочена')], max_length=20)),
                ('model_photo', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
