# Generated by Django 3.0.8 on 2020-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_use',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
