# Generated by Django 3.0.8 on 2020-07-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200712_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='model_photo',
            field=models.ImageField(blank=True, default='stars.png', upload_to=''),
        ),
    ]
