# Generated by Django 3.0.8 on 2020-07-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200712_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='model_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(max_length=14),
        ),
    ]
