# Generated by Django 3.0.8 on 2020-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20200712_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Неактивована', 'Неактивована'), ('Активована', 'Активована'), ('Прострочена', 'Прострочена')], max_length=20),
        ),
    ]
